parameters:
#    accolade_crm_intranet.example.class: AccoladeCRM\IntranetBundle\Example

services:
#    accolade_crm_intranet.example:
#        class: %accolade_crm_intranet.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
